In [3]:
import pandas as pd
import numpy as np

## 2023 March Madness Stats

### First Four

In [4]:
first_four = pd.read_csv('first_four.csv')

In [5]:
first_four = first_four[['Rk', 'Team', 'Seed', 'Date', 'PTS', 'Opp', 'Opp Seed',
       'Result', 'Round', 'Region', 'FG', 'FGA', 'FG%', '2P', '2PA',
       '2P%', '3P', '3PA', '3P%', 'FT', 'FTA', 'FT%']]

### Round One

In [6]:
round_one = pd.read_csv('round_of_64.csv')

In [8]:
round_one = round_one[['Rk', 'Team', 'Seed', 'Date', 'PTS', 'Opp', 'Opp Seed',
       'Result', 'Round', 'Region', 'FG', 'FGA', 'FG%', '2P', '2PA',
       '2P%', '3P', '3PA', '3P%', 'FT', 'FTA', 'FT%']]

In [9]:
round_one

,Rk,Team,Seed,Date,PTS,Opp,Opp Seed,Result,Round,Region,...,FG%,2P,2PA,2P%,3P,3PA,3P%,FT,FTA,FT%
0,1,Alabama,1,2023-03-16 NCAA,96,Texas A&Mâ€“Corpus Christi,16,W 96-75,Rnd of 64,South,...,0.471,18,37,0.486,15,33,0.455,15,23,0.652
1,2,Kansas,1,2023-03-16 NCAA,96,Howard,16,W 96-68,Rnd of 64,West,...,0.521,29,51,0.569,9,22,0.409,11,13,0.846
2,3,Connecticut,4,2023-03-17 NCAA,87,Iona,13,W 87-63,Rnd of 64,West,...,0.485,21,41,0.512,11,25,0.440,12,14,0.857
3,4,UCLA,2,2023-03-16 NCAA,86,UNC Asheville,15,W 86-53,Rnd of 64,West,...,0.540,29,47,0.617,5,16,0.313,13,17,0.765
4,5,Auburn,9,2023-03-16 NCAA,83,Iowa,8,W 83-75,Rnd of 64,Midwest,...,0.460,21,41,0.512,8,22,0.364,17,22,0.773
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,60,UNC Asheville,15,2023-03-16 NCAA,53,UCLA,2,L 53-86,Rnd of 64,West,...,0.373,13,31,0.419,6,20,0.300,9,13,0.692
60,61,Northern Kentucky,16,2023-03-16 NCAA,52,Houston,1,L 52-63,Rnd of 64,Midwest,...,0.275,14,36,0.389,5,33,0.152,9,10,0.900
61,62,VCU,12,2023-03-17 NCAA,51,St. Mary's (CA),5,L 51-63,Rnd of 64,West,...,0.367,13,35,0.371,5,14,0.357,10,16,0.625
62,63,Oral Roberts,12,2023-03-16 NCAA,51,Duke,5,L 51-74,Rnd of 64,East,...,0.302,11,31,0.355,8,32,0.250,5,8,0.625
63,64,Iowa State,6,2023-03-17 NCAA,41,Pittsburgh,11,L 41-59,Rnd of 64,Midwest,...,0.233,12,39,0.308,2,21,0.095,11,19,0.579

### Round Two

In [10]:
round_two = pd.read_csv('round_of_32.csv')

In [11]:
round_two = round_two[['Rk', 'Team', 'Seed', 'Date', 'PTS', 'Opp', 'Opp Seed',
       'Result', 'Round', 'Region', 'FG', 'FGA', 'FG%', '2P', '2PA',
       '2P%', '3P', '3PA', '3P%', 'FT', 'FTA', 'FT%']]

In [12]:
round_two

,Rk,Team,Seed,Date,PTS,Opp,Opp Seed,Result,Round,Region,...,FG%,2P,2PA,2P%,3P,3PA,3P%,FT,FTA,FT%
0,1,Miami (FL),5,2023-03-19 NCAA,85,Indiana,4,W 85-69,Rnd of 32,Midwest,...,0.486,25,47,0.532,9,23,0.391,8,13,0.615
1,2,Creighton,6,2023-03-19 NCAA,85,Baylor,3,W 85-76,Rnd of 32,South,...,0.473,15,31,0.484,11,24,0.458,22,22,1.000
2,3,Gonzaga,3,2023-03-19 NCAA,84,TCU,6,W 84-81,Rnd of 32,West,...,0.448,22,42,0.524,8,25,0.320,16,25,0.640
3,4,Xavier,3,2023-03-19 NCAA,84,Pittsburgh,11,W 84-73,Rnd of 32,Midwest,...,0.476,22,39,0.564,8,24,0.333,16,26,0.615
4,5,TCU,6,2023-03-19 NCAA,81,Gonzaga,3,L 81-84,Rnd of 32,West,...,0.448,21,42,0.500,9,25,0.360,12,20,0.600
5,6,Houston,1,2023-03-18 NCAA,81,Auburn,9,W 81-64,Rnd of 32,Midwest,...,0.417,18,38,0.474,7,22,0.318,24,29,0.828
6,7,Florida Atlantic,9,2023-03-19 NCAA,78,FDU,16,W 78-70,Rnd of 32,East,...,0.408,20,40,0.500,9,31,0.290,11,18,0.611
7,8,Princeton,15,2023-03-18 NCAA,78,Missouri,7,W 78-63,Rnd of 32,South,...,0.435,15,29,0.517,12,33,0.364,12,15,0.800
8,9,Baylor,3,2023-03-19 NCAA,76,Creighton,6,L 76-85,Rnd of 32,South,...,0.460,24,41,0.585,5,22,0.227,13,19,0.684
9,10,Kansas State,3,2023-03-19 NCAA,75,Kentucky,6,W 75-69,Rnd of 32,East,...,0.481,21,33,0.636,5,21,0.238,18,22,0.818
10,11,San Diego State,5,2023-03-18 NCAA,75,Furman,13,W 75-52,Rnd of 32,South,...,0.500,23,38,0.605,6,20,0.300,11,14,0.786
11,12,Pittsburgh,11,2023-03-19 NCAA,73,Xavier,3,L 73-84,Rnd of 32,Midwest,...,0.386,21,50,0.420,6,20,0.300,13,20,0.650
12,13,Alabama,1,2023-03-18 NCAA,73,Maryland,8,W 73-51,Rnd of 32,South,...,0.397,17,37,0.459,6,21,0.286,21,28,0.750
13,14,Arkansas,8,2023-03-18 NCAA,72,Kansas,1,W 72-71,Rnd of 32,West,...,0.414,21,43,0.488,3,15,0.200,21,26,0.808
14,15,Texas,2,2023-03-18 NCAA,71,Penn State,10,W 71-66,Rnd of 32,Midwest,...,0.508,30,48,0.625,1,13,0.077,8,11,0.727
15,16,Kansas,1,2023-03-18 NCAA,71,Arkansas,8,L 71-72,Rnd of 32,West,...,0.480,19,37,0.514,5,13,0.385,18,25,0.720
16,17,Connecticut,4,2023-03-19 NCAA,70,St. Mary's (CA),5,W 70-55,Rnd of 32,West,...,0.540,17,28,0.607,10,22,0.455,6,7,0.857
17,18,FDU,16,2023-03-19 NCAA,70,Florida Atlantic,9,L 70-78,Rnd of 32,East,...,0.380,18,40,0.450,9,31,0.290,7,10,0.700
18,19,Michigan State,7,2023-03-19 NCAA,69,Marquette,2,W 69-60,Rnd of 32,East,...,0.444,22,38,0.579,2,16,0.125,19,23,0.826
19,20,Indiana,4,2023-03-19 NCAA,69,Miami (FL),5,L 69-85,Rnd of 32,Midwest,...,0.413,18,38,0.474,8,25,0.320,9,14,0.643
20,21,Kentucky,6,2023-03-19 NCAA,69,Kansas State,3,L 69-75,Rnd of 32,East,...,0.413,22,43,0.512,4,20,0.200,13,17,0.765
21,22,UCLA,2,2023-03-18 NCAA,68,Northwestern,7,W 68-63,Rnd of 32,West,...,0.500,16,29,0.552,6,15,0.400,18,21,0.857
22,23,Penn State,10,2023-03-18 NCAA,66,Texas,2,L 66-71,Rnd of 32,Midwest,...,0.417,17,32,0.531,8,28,0.286,8,11,0.727
23,24,Tennessee,4,2023-03-18 NCAA,65,Duke,5,W 65-52,Rnd of 32,East,...,0.404,14,36,0.389,9,21,0.429,10,13,0.769
24,25,Auburn,9,2023-03-18 NCAA,64,Houston,1,L 64-81,Rnd of 32,Midwest,...,0.377,15,37,0.405,5,16,0.313,19,36,0.528
25,26,Northwestern,7,2023-03-18 NCAA,63,UCLA,2,L 63-68,Rnd of 32,West,...,0.373,16,37,0.432,6,22,0.273,13,15,0.867
26,27,Missouri,7,2023-03-18 NCAA,63,Princeton,15,L 63-78,Rnd of 32,South,...,0.410,19,39,0.487,6,22,0.273,7,7,1.000
27,28,Marquette,2,2023-03-19 NCAA,60,Michigan State,7,L 60-69,Rnd of 32,East,...,0.385,9,25,0.360,11,27,0.407,9,14,0.643
28,29,St. Mary's (CA),5,2023-03-19 NCAA,55,Connecticut,4,L 55-70,Rnd of 32,West,...,0.388,15,35,0.429,4,14,0.286,13,19,0.684
29,30,Furman,13,2023-03-18 NCAA,52,San Diego State,5,L 52-75,Rnd of 32,South,...,0.320,10,24,0.417,6,26,0.231,14,18,0.778
30,31,Duke,5,2023-03-18 NCAA,52,Tennessee,4,L 52-65,Rnd of 32,East,...,0.429,15,27,0.556,6,22,0.273,4,7,0.571
31,32,Maryland,8,2023-03-18 NCAA,51,Alabama,1,L 51-73,Rnd of 32,South,...,0.352,18,46,0.391,1,8,0.125,12,21,0.571

### Sweet 16

In [13]:
sweet_16 = pd.read_csv('sweet_16.csv')

In [14]:
sweet_16 = sweet_16[['Rk', 'Team', 'Seed', 'Date', 'PTS', 'Opp', 'Opp Seed',
       'Result', 'Round', 'Region', 'FG', 'FGA', 'FG%', '2P', '2PA',
       '2P%', '3P', '3PA', '3P%', 'FT', 'FTA', 'FT%']]

In [15]:
sweet_16

,Rk,Team,Seed,Date,PTS,Opp,Opp Seed,Result,Round,Region,...,FG%,2P,2PA,2P%,3P,3PA,3P%,FT,FTA,FT%
0,1,Kansas State,3,2023-03-23 NCAA,98,Michigan State,7,W 98-93 (OT),Rnd of 16,East,...,0.559,27,44,0.614,11,24,0.458,11,16,0.688
1,2,Michigan State,7,2023-03-23 NCAA,93,Kansas State,3,L 93-98 (OT),Rnd of 16,East,...,0.492,18,38,0.474,13,25,0.520,18,22,0.818
2,3,Miami (FL),5,2023-03-24 NCAA,89,Houston,1,W 89-75,Rnd of 16,Midwest,...,0.517,20,35,0.571,11,25,0.440,16,19,0.842
3,4,Connecticut,4,2023-03-23 NCAA,88,Arkansas,8,W 88-65,Rnd of 16,West,...,0.574,22,34,0.647,9,20,0.450,17,21,0.810
4,5,Creighton,6,2023-03-24 NCAA,86,Princeton,15,W 86-75,Rnd of 16,South,...,0.582,23,31,0.742,9,24,0.375,13,16,0.813
5,6,Texas,2,2023-03-24 NCAA,83,Xavier,3,W 83-71,Rnd of 16,Midwest,...,0.525,25,49,0.510,7,12,0.583,12,19,0.632
6,7,Gonzaga,3,2023-03-23 NCAA,79,UCLA,2,W 79-76,Rnd of 16,West,...,0.500,26,48,0.542,6,16,0.375,9,17,0.529
7,8,UCLA,2,2023-03-23 NCAA,76,Gonzaga,3,L 76-79,Rnd of 16,West,...,0.418,21,49,0.429,7,18,0.389,13,16,0.813
8,9,Houston,1,2023-03-24 NCAA,75,Miami (FL),5,L 75-89,Rnd of 16,Midwest,...,0.375,15,33,0.455,9,31,0.290,18,20,0.900
9,10,Princeton,15,2023-03-24 NCAA,75,Creighton,6,L 75-86,Rnd of 16,South,...,0.462,21,44,0.477,9,21,0.429,6,10,0.600
10,11,Xavier,3,2023-03-24 NCAA,71,Texas,2,L 71-83,Rnd of 16,Midwest,...,0.438,21,47,0.447,7,17,0.412,8,12,0.667
11,12,San Diego State,5,2023-03-24 NCAA,71,Alabama,1,W 71-64,Rnd of 16,South,...,0.377,20,52,0.385,6,17,0.353,13,22,0.591
12,13,Arkansas,8,2023-03-23 NCAA,65,Connecticut,4,L 65-88,Rnd of 16,West,...,0.317,15,47,0.319,5,16,0.313,20,27,0.741
13,14,Alabama,1,2023-03-24 NCAA,64,San Diego State,5,L 64-71,Rnd of 16,South,...,0.324,20,44,0.455,3,27,0.111,15,20,0.750
14,15,Florida Atlantic,9,2023-03-23 NCAA,62,Tennessee,4,W 62-55,Rnd of 16,East,...,0.420,13,23,0.565,8,27,0.296,12,16,0.750
15,16,Tennessee,4,2023-03-23 NCAA,55,Florida Atlantic,9,L 55-62,Rnd of 16,East,...,0.333,15,40,0.375,6,23,0.261,7,12,0.583

### Elite 8

In [17]:
elite_8 = pd.read_csv('elite_8.csv')

In [18]:
elite_8 = elite_8[['Rk', 'Team', 'Seed', 'Date', 'PTS', 'Opp', 'Opp Seed',
       'Result', 'Round', 'Region', 'FG', 'FGA', 'FG%', '2P', '2PA',
       '2P%', '3P', '3PA', '3P%', 'FT', 'FTA', 'FT%']]

In [19]:
elite_8

,Rk,Team,Seed,Date,PTS,Opp,Opp Seed,Result,Round,Region,...,FG%,2P,2PA,2P%,3P,3PA,3P%,FT,FTA,FT%
0,1,Miami (FL),5,2023-03-26 NCAA,88,Texas,2,W 88-81,Rnd of 8,Midwest,...,0.592,27,41,0.659,2,8,0.250,28,32,0.875
1,2,Connecticut,4,2023-03-25 NCAA,82,Gonzaga,3,W 82-54,Rnd of 8,West,...,0.417,19,41,0.463,11,31,0.355,11,14,0.786
2,3,Texas,2,2023-03-26 NCAA,81,Miami (FL),5,L 81-88,Rnd of 8,Midwest,...,0.500,20,35,0.571,10,25,0.400,11,15,0.733
3,4,Florida Atlantic,9,2023-03-25 NCAA,79,Kansas State,3,W 79-76,Rnd of 8,East,...,0.481,17,31,0.548,9,23,0.391,18,22,0.818
4,5,Kansas State,3,2023-03-25 NCAA,76,Florida Atlantic,9,L 76-79,Rnd of 8,East,...,0.466,17,36,0.472,10,22,0.455,12,18,0.667
5,6,San Diego State,5,2023-03-26 NCAA,57,Creighton,6,W 57-56,Rnd of 8,South,...,0.379,22,53,0.415,3,13,0.231,4,6,0.667
6,7,Creighton,6,2023-03-26 NCAA,56,San Diego State,5,L 56-57,Rnd of 8,South,...,0.400,20,38,0.526,2,17,0.118,10,11,0.909
7,8,Gonzaga,3,2023-03-25 NCAA,54,Connecticut,4,L 54-82,Rnd of 8,West,...,0.333,18,40,0.450,2,20,0.100,12,22,0.545

### Final Four and Championship Game Stat

In [20]:
final_four = pd.read_csv('final_four.csv')

In [21]:
final_four = final_four[['Rk', 'Team', 'Seed', 'Date', 'PTS', 'Opp', 'Opp Seed',
       'Result', 'Round', 'Region', 'FG', 'FGA', 'FG%', '2P', '2PA',
       '2P%', '3P', '3PA', '3P%', 'FT', 'FTA', 'FT%']]

In [22]:
final_four

,Rk,Team,Seed,Date,PTS,Opp,Opp Seed,Result,Round,Region,...,FG%,2P,2PA,2P%,3P,3PA,3P%,FT,FTA,FT%
0,1,Connecticut,4,2023-04-03 NCAA,76,San Diego State,5,W 76-59,National Final,West,...,0.434,17,36,0.472,6,17,0.353,24,27,0.889
1,2,San Diego State,5,2023-04-01 NCAA,72,Florida Atlantic,9,W 72-71,National Semi,South,...,0.439,16,39,0.410,9,18,0.500,13,22,0.591
2,3,Connecticut,4,2023-04-01 NCAA,72,Miami (FL),5,W 72-59,National Semi,West,...,0.491,19,31,0.613,9,26,0.346,7,13,0.538
3,4,Florida Atlantic,9,2023-04-01 NCAA,71,San Diego State,5,L 71-72,National Semi,East,...,0.442,14,30,0.467,9,22,0.409,16,21,0.762
4,5,San Diego State,5,2023-04-03 NCAA,59,Connecticut,4,L 59-76,National Final,South,...,0.322,13,36,0.361,6,23,0.261,15,20,0.750
5,6,Miami (FL),5,2023-04-01 NCAA,59,Connecticut,4,L 59-72,National Semi,Midwest,...,0.323,13,42,0.310,7,20,0.350,12,12,1.000